// FOR WIFI + BT
// SOME, IF NOT ALL DRIVERS REQUIRE SEMAPHORE LOGIC TO CONTROL ACCESS TO WRITES
// WIRELESS COMMS ARE HEAVILY RELIANT ON TWO WAY COMMS SO MUTEXING IS VITAL

// UNLIKE MOUSE, KB AND OTHER PERIPHERALS WHICH ARE NORMALLY ONE-WAY COMMS
